# Generated by Django 4.2.4 on 2023-08-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitCounter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimesVisited',
            new_name='Visit',
        ),
    ]
