# Generated by Django 4.2.4 on 2023-08-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitCounter', '0002_rename_timesvisited_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='id',
        ),
        migrations.AddField(
            model_name='visit',
            name='userid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='username',
            field=models.CharField(default='Guest', max_length=20),
        ),
    ]
